version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-coder
    command: --secure-file-priv=""
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER_1},${MYSQL_USER_2},${MYSQL_USER_3},${MYSQL_USER_4},${MYSQL_USER_5}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_1},${MYSQL_PASSWORD_2},${MYSQL_PASSWORD_3},${MYSQL_PASSWORD_4},${MYSQL_PASSWORD_5}
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./RestAnalytics_DataBase/csv:/home/app/csv
      - ./RestAnalytics_DataBase/scripts:/home/app/scripts
      - ./RestAnalytics_DataBase/backup:/home/app/backup
    working_dir: /home/app
    env_file:
      - ./.env