INSERT INTO dishes VALUES ('1', 'Classic Burger', 'Deliciosa hamburguesa clásica con carne jugosa, pan suave, lechuga, tomate y queso.', 'Hamburguesa', '9.99', '1');
INSERT INTO dishes VALUES ('2', 'Cheeseburger Supreme', 'Hamburguesa con doble carne, queso fundido, tocino crujiente y salsa especial.', 'Hamburguesa', '12.99', '1');
INSERT INTO dishes VALUES ('3', 'Spicy Chicken Sandwich', 'Sándwich de pollo picante con lechuga, tomate y mayonesa de chipotle.', 'Sándwich', '10.99', '1');
INSERT INTO dishes VALUES ('4', 'Vegetarian Deluxe', 'Burger vegetariana con una sabrosa mezcla de verduras, queso y aderezo especial.', 'Hamburguesa', '9.99', '1');
INSERT INTO dishes VALUES ('5', 'Eggs Benedict', 'Huevos pochados sobre muffin inglés con lonchas de jamón cubiertos de salsa holandesa.', 'Desayuno', '11.99', '2');
INSERT INTO dishes VALUES ('6', 'French Toast', 'Tostadas francesas esponjosas servidas con jarabe de arce y mantequilla.', 'Desayuno', '8.99', '2');
INSERT INTO dishes VALUES ('7', 'Cobb Salad', 'Ensalada clásica con pollo a la parrilla, aguacate, huevo, tomate y aderezo de queso azul.', 'Ensalada', '10.99', '2');
INSERT INTO dishes VALUES ('8', 'Caramel Macchiato', 'Café espresso con leche caliente y espuma de leche, endulzado con caramelo.', 'Café', '4.99', '3');
INSERT INTO dishes VALUES ('9', 'Croissant de jamón y queso', 'Croissant horneado con jamón y queso fundido.', 'Desayuno', '3.99', '3');
INSERT INTO dishes VALUES ('10', 'Chocolate Chip Muffin', 'Muffin de chocolate con chispas, perfecto para acompañar el café.', 'Postre', '2.99', '3');
INSERT INTO dishes VALUES ('11', 'Taco al Pastor', 'Taco mexicano con carne de cerdo marinada, piña, cebolla y cilantro.', 'Taco', '3.5', '4');
INSERT INTO dishes VALUES ('12', 'Taco de Barbacoa', 'Taco de carne de res jugosa y tierna cocinada a fuego lento, con cebolla y cilantro.', 'Taco', '3.5', '4');
INSERT INTO dishes VALUES ('13', 'Quesadilla de Pollo', 'Quesadilla de tortilla de harina con pollo a la parrilla, queso fundido y guacamole.', 'Plato Principal', '9.99', '4');
INSERT INTO dishes VALUES ('14', 'Margherita Pizza', 'Pizza clásica italiana con salsa de tomate, mozzarella fresca y albahaca.', 'Pizza', '12.99', '5');
INSERT INTO dishes VALUES ('15', 'Pepperoni Lovers', 'Pizza con salsa de tomate, queso mozzarella y abundante pepperoni.', 'Pizza', '14.99', '5');
INSERT INTO dishes VALUES ('16', 'Hawaiian Delight', 'Pizza con jamón, piña, salsa de tomate y queso mozzarella.', 'Pizza', '13.99', '5');
INSERT INTO dishes VALUES ('17', 'Hot Wings', 'Alitas de pollo picantes servidas con salsa de tu elección y bastones de apio.', 'Aperitivo', '8.99', '6');
INSERT INTO dishes VALUES ('18', 'Crispy Chicken Tenders', 'Tiras de pollo crujientes servidas con papas fritas y salsa de mostaza y miel.', 'Plato Principal', '10.99', '6');
INSERT INTO dishes VALUES ('19', 'Chicken Caesar Wrap', 'Wrap de pollo a la parrilla, lechuga, tomate, queso parmesano y aderezo Caesar.', 'Sándwich', '9.99', '6');
INSERT INTO dishes VALUES ('20', 'Double Cheeseburger', 'Hamburguesa doble con queso cheddar fundido, pepinillos y salsa especial.', 'Hamburguesa', '11.99', '7');
INSERT INTO dishes VALUES ('21', 'Bacon Mushroom Melt', 'Hamburguesa con tocino crujiente, champiñones salteados y queso suizo fundido.', 'Hamburguesa', '12.99', '7');
INSERT INTO dishes VALUES ('22', 'Avocado Turkey Burger', 'Hamburguesa de pavo jugosa con aguacate, lechuga, tomate y mayonesa.', 'Hamburguesa', '10.99', '7');
INSERT INTO dishes VALUES ('23', 'Sashimi Deluxe', 'Selección de pescado crudo fresco en finas lonchas, servido con salsa de soja y wasabi.', 'Sushi', '18.99', '8');
INSERT INTO dishes VALUES ('24', 'California Roll', 'Roll clásico de sushi con cangrejo de imitación, aguacate y pepino.', 'Sushi', '9.99', '8');
INSERT INTO dishes VALUES ('25', 'Dragon Roll', 'Roll de sushi con langostinos tempura, aguacate y salsa de anguila.', 'Sushi', '14.99', '8');
INSERT INTO dishes VALUES ('26', 'Spaghetti Bolognese', 'Spaghetti con salsa de carne a la boloñesa y queso parmesano rallado.', 'Pasta', '11.99', '9');
INSERT INTO dishes VALUES ('27', 'Lasagna Classica', 'Lasaña casera con capas de pasta, carne, salsa de tomate y queso gratinado.', 'Pasta', '13.99', '9');
INSERT INTO dishes VALUES ('28', 'Gnocchi al Pesto', 'Gnocchi caseros con salsa de pesto fresco, piñones y queso parmesano.', 'Pasta', '12.99', '9');
INSERT INTO dishes VALUES ('29', 'Roasted Chicken', 'Pollo asado jugoso acompañado de puré de papas y vegetales asados.', 'Plato Principal', '13.99', '10');
INSERT INTO dishes VALUES ('30', 'Honey Mustard Chicken', 'Pechuga de pollo a la parrilla con salsa de mostaza y miel, servida con arroz.', 'Plato Principal', '12.99', '10');
INSERT INTO dishes VALUES ('31', 'Chicken Caesar Salad', 'Ensalada César con pollo a la parrilla, lechuga romana, queso parmesano y aderezo Caesar.', 'Ensalada', '10.99', '10');
INSERT INTO dishes VALUES ('32', 'BBQ Bacon Burger', 'Hamburguesa con salsa BBQ, tocino crujiente, cebolla a la parrilla y queso cheddar.', 'Hamburguesa', '11.99', '1');
INSERT INTO dishes VALUES ('33', 'Mushroom Swiss Burger', 'Hamburguesa con champiñones salteados, queso suizo y salsa especial.', 'Hamburguesa', '12.99', '1');
INSERT INTO dishes VALUES ('34', 'Chicken Avocado Wrap', 'Wrap de pollo a la parrilla, aguacate, lechuga, tomate y aderezo de cilantro.', 'Sándwich', '9.99', '1');
INSERT INTO dishes VALUES ('35', 'Onion Rings', 'Aros de cebolla crujientes y dorados, acompañados de salsa BBQ.', 'Acompañamiento', '4.99', '1');
INSERT INTO dishes VALUES ('36', 'Avocado Toast', 'Tostada de pan de centeno con aguacate, huevo pochado y semillas de chía.', 'Desayuno', '9.99', '2');
INSERT INTO dishes VALUES ('37', 'Greek Salad', 'Ensalada griega con pepino, tomate, aceitunas kalamata, queso feta y aderezo de limón.', 'Ensalada', '10.99', '2');
INSERT INTO dishes VALUES ('38', 'Spinach and Feta Omelette', 'Omelette de espinacas y queso feta, servido con pan tostado.', 'Desayuno', '8.99', '2');
INSERT INTO dishes VALUES ('39', 'Blueberry Pancakes', 'Panqueques esponjosos con arándanos frescos y jarabe de arce.', 'Desayuno', '7.99', '2');
INSERT INTO dishes VALUES ('40', 'Iced Caramel Latte', 'Latte helado con café espresso, leche, caramelo y hielo.', 'Café', '5.99', '3');
INSERT INTO dishes VALUES ('41', 'Bagel with Lox', 'Bagel tostado con salmón ahumado, queso crema, rodajas de pepino y eneldo.', 'Desayuno', '9.99', '3');
INSERT INTO dishes VALUES ('42', 'Red Velvet Cupcake', 'Cupcake de terciopelo rojo con crema de queso y decoración de chocolate.', 'Postre', '3.99', '3');
INSERT INTO dishes VALUES ('43', 'Affogato', 'Café espresso servido sobre una bola de helado de vainilla.', 'Postre', '6.99', '3');
INSERT INTO dishes VALUES ('44', 'Carnitas Burrito', 'Burrito relleno de carne de cerdo deshebrada, frijoles, arroz y salsa verde.', 'Plato Principal', '10.99', '4');
INSERT INTO dishes VALUES ('45', 'Chorizo Tacos', 'Tacos de chorizo picante con cebolla, cilantro y salsa de tomate asada.', 'Taco', '4.5', '4');
INSERT INTO dishes VALUES ('46', 'Guacamole and Chips', 'Delicioso guacamole casero con totopos de maíz recién hechos.', 'Aperitivo', '6.99', '4');
INSERT INTO dishes VALUES ('47', 'Mexican Street Corn', 'Elote asado a la parrilla con mayonesa, queso fresco y chile en polvo.', 'Aperitivo', '5.99', '4');
INSERT INTO dishes VALUES ('48', 'Caprese Salad', 'Ensalada caprese con tomates, mozzarella fresca, albahaca y aceite de oliva.', 'Ensalada', '9.99', '5');
INSERT INTO dishes VALUES ('49', 'Meat Lover`s Pizza', 'Pizza con salsa de tomate, pepperoni, salchicha, tocino y jamón.', 'Pizza', '14.99', '5');
INSERT INTO dishes VALUES ('50', 'Vegetarian Pizza', 'Pizza con salsa de tomate, mozzarella, champiñones, pimientos y aceitunas.', 'Pizza', '12.99', '5');
INSERT INTO dishes VALUES ('51', 'Garlic Bread', 'Pan de ajo horneado con mantequilla de ajo y espolvoreado con perejil.', 'Aperitivo', '4.99', '5');
INSERT INTO dishes VALUES ('52', 'BBQ Chicken Wings', 'Alitas de pollo bañadas en salsa BBQ y servidas con bastones de zanahoria y apio.', 'Aperitivo', '8.99', '6');
INSERT INTO dishes VALUES ('53', 'Crispy Chicken Salad', 'Ensalada con pollo crujiente, lechuga mixta, tomate, pepino y aderezo ranch.', 'Ensalada', '9.99', '6');
INSERT INTO dishes VALUES ('54', 'Spicy Chicken Sandwich', 'Sándwich de pollo picante con queso pepper jack, jalapeños y salsa de chipotle.', 'Sándwich', '10.99', '6');
INSERT INTO dishes VALUES ('55', 'Sweet Potato Fries', 'Bastones de camote crujientes servidos con alioli de cilantro.', 'Acompañamiento', '5.99', '6');
INSERT INTO dishes VALUES ('56', 'Mushroom Swiss Burger', 'Hamburguesa con champiñones salteados, queso suizo y salsa especial.', 'Hamburguesa', '12.99', '7');
INSERT INTO dishes VALUES ('57', 'Bacon Cheese Fries', 'Papas fritas cubiertas con queso cheddar fundido y tocino crujiente.', 'Acompañamiento', '6.99', '7');
INSERT INTO dishes VALUES ('58', 'Onion Rings', 'Aros de cebolla crujientes y dorados, acompañados de salsa de chipotle.', 'Acompañamiento', '4.99', '7');
INSERT INTO dishes VALUES ('59', 'Oreo Milkshake', 'Batido cremoso de helado de vainilla con trozos de galleta Oreo.', 'Bebida', '6.99', '7');
INSERT INTO dishes VALUES ('60', 'Rainbow Roll', 'Roll de sushi con pescado variado, aguacate y salsa de anguila.', 'Sushi', '15.99', '8');
INSERT INTO dishes VALUES ('61', 'Tempura Shrimp Roll', 'Roll de sushi con camarones tempura, aguacate y salsa de anguila.', 'Sushi', '13.99', '8');
INSERT INTO dishes VALUES ('62', 'Spicy Tuna Roll', 'Roll de sushi picante con atún, aguacate y pepino.', 'Sushi', '11.99', '8');
INSERT INTO dishes VALUES ('63', 'Miso Soup', 'Sopa de miso tradicional con tofu, algas y cebollín.', 'Sopa', '3.99', '8');
INSERT INTO dishes VALUES ('64', 'Fettuccine Alfredo', 'Fettuccine con salsa cremosa de queso parmesano.', 'Pasta', '12.99', '9');
INSERT INTO dishes VALUES ('65', 'Chicken Parmesan', 'Pechuga de pollo empanizada con salsa marinara y queso derretido, servida sobre espaguetis.', 'Plato Principal', '14.99', '9');
INSERT INTO dishes VALUES ('66', 'Caprese Salad', 'Ensalada caprese con tomates frescos, mozzarella y hojas de albahaca.', 'Ensalada', '9.99', '9');
INSERT INTO dishes VALUES ('67', 'Tiramisu', 'Postre italiano clásico hecho con bizcochos, café, crema de mascarpone y cacao.', 'Postre', '7.99', '9');
INSERT INTO dishes VALUES ('68', 'BBQ Chicken Wings', 'Alitas de pollo bañadas en salsa BBQ y servidas con bastones de apio y zanahoria.', 'Aperitivo', '8.99', '10');
INSERT INTO dishes VALUES ('69', 'Grilled Chicken Caesar Salad', 'Ensalada César con pollo a la parrilla, lechuga romana, crutones y aderezo Caesar.', 'Ensalada', '10.99', '10');
INSERT INTO dishes VALUES ('70', 'Chicken Quesadilla', 'Quesadilla de pollo con queso cheddar derretido, cebolla y pimientos.', 'Plato Principal', '9.99', '10');
INSERT INTO dishes VALUES ('71', 'Lime Pie', 'Tarta de lima con una base de galleta y crema de lima.', 'Postre', '6.99', '10');

SELECT * FROM dishes;